blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/THF-studio/apps-habit-tracker/tree/main/.github/ISSUE_TEMPLATE
    about: Suggest a new feature for the app
